global class harvHttpReqHeaderModel {
    
    	global string harvMethod = 'GET';
        global string harvContentType = 'Content-Type'+','+'application/json';
        global string harvAccept  = 'Accept'+','+'application/json';
        global string harvUserAgent = 'User-Agent'+','+'MyApp (ivan@exah.co.za)';
    	global string harvAuthorization = 'Authorization'+','+'Bearer 1848717.pt.QDXsfn5UNvNEkjFmgAiSJ6yxfUN2iF39Q47eAeEM9MByz47jwqvrH725wcDQzqcYiM-_Uh4g6BQ_fzv58EIUvw';
        global string harvAccId = 'Harvest-Account-Id'+','+'1055284';
       
}